import uuid
from typing import Protocol, Any
from datetime import datetime
from app.models.todo import Todo
from app.models.user import User, RefreshToken
from app.schemas.todo import TodoCreate, TodoUpdate


class TodoRepositoryProto(Protocol):
    async def create(self, obj_in: TodoCreate, user_id: uuid.UUID) -> Todo: ...
    async def get_by_id(self, todo_id: int, user_id: uuid.UUID) -> Todo | None: ...
    async def get_multi(self, skip: int, limit: int, user_id: uuid.UUID) -> list[Todo]: ...
    async def get_by_title(self, title: str, user_id: uuid.UUID) -> Todo | None: ...
    async def update(self, db_obj: Todo, obj_in: TodoUpdate) -> Todo: ...
    async def delete(self, db_obj: Todo) -> None: ...


class UserRepositoryProto(Protocol):
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def get_user_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def create_user(self, email: str, hashed_password: str) -> User: ...
    async def create_refresh_token(
        self, user_id: uuid.UUID, token_hash: str, expires_at: datetime
    ) -> RefreshToken: ...
    async def get_refresh_token_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke_refresh_token_by_hash(self, token_hash: str) -> None: ...
    async def revoke_all_user_tokens(self, user_id: uuid.UUID) -> None: ...